# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[┌─](white) $os$username$hostname$aws $fill $status$battery$memory_usage$time
[│](white) $all
[└─$shlvl$character](white)
"""

[fill]
symbol = "─"
style = "white"

[aws]
format = "via [$symbol($profile)( \\($region\\))( \\[$duration\\])( \\[$expiration_symbol\\])]($style)"
symbol = "  "
expiration_symbol = "[](bold red)"

[azure]
symbol = "󰠅 "

[battery]
unknown_symbol = "󰂑 "
[[battery.display]]
threshold = 20
style = "red"
[[battery.display]]
threshold = 40
style = "orange"
[[battery.display]]
threshold = 60
style = "yellow"
[[battery.display]]
threshold = 80
style = "green"
[[battery.display]]
threshold = 100
style = "white"

[buf]
disabled = true
symbol = " "

[bun]
disabled = true

[c]
symbol = " "

[character]
success_symbol = ""
error_symbol = "[ ](bold red)"

[cmake]
disabled = true

[cobol]
disabled = true

[cmd_duration]
format = "runtime [$duration]($style) "

[conda]
symbol = "󱥸 "
style = "bold green"
ignore_base = false

[container]
symbol = " "

[crystal]
disabled = true
symbol = "󰬯 "

[daml]
disabled = true

[dart]
disabled = true
symbol = " "

[deno]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = ".../"
truncate_to_repo = true
read_only = " 󰌾"

[direnv]

[docker_context]
symbol = "  "

[dotnet]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[erlang]
disabled = true
symbol = " "

[fennel]
disabled = true
symbol = " "

[fossil_branch]
disabled = true
symbol = "󰹧 "

[fossil_metrics]
disabled = true

[gcloud]
symbol = "󱇶 "
format = "on [$symbol$active(@$domain)(\\($region\\))(\\($project\\))]($style) "

[git_branch]
symbol = "󰹧 "
format = "on [$symbol$branch(:$remote_branch)]($style) "
truncation_length = 4
truncation_symbol = "..."

[git_commit]
commit_hash_length = 5
tag_symbol = " "

[git_state]

[git_metrics]
disabled = false

[git_status]

[golang]
symbol = " "

[guix_shell]
disabled = true
symbol = " "

[gradle]
disabled = true
symbol =" "

[haskell]
disabled = true
symbol = " "

[haxe]
disabled = true
symbol = " "

[helm]
disabled = true
symbol = "󰠳 "

[hg_branch]
disabled = true
symbol = "󰹧 "

[hostname]
ssh_only = false
ssh_symbol = " "
format ="[$ssh_symbol$hostname]($style) "
style = "bold green dimmed"
detect_env_vars = ['!TMUX', 'SSH_CONNECTION']
disabled = false

[java]
disabled = true
symbol = " "

[jobs]
symbol = "+ "

[julia]
symbol = " "

[kotlin]
disabled = true
symbol = " "

[line_break]
disabled = true

[kubernetes]
disabled = false
symbol = "󱃾 "

[localip]
ssh_only = false
format = "@[$localipv4]($style) "

[lua]
disabled = true
symbol = " "

[memory_usage]
disabled = false
threshold = 85
format = "with $symbol[$ram_pct(|$swap_pct)]($style) "
symbol = "󰍛 "
style = "red bold"

[meson]
disabled = true
symbol = "󰔷 "

[nim]
disabled = true
symbol = "󰆥 "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = true
symbol = "󰎙 "

[ocaml]
disabled = true
symbol = " "

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = false

[os.symbols]
Alpaquita = " "
AlmaLinux = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = "  "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏓 "

[perl]
symbol = " "

[php]
disabled = true
symbol = " "

[pijul_channel]
disabled = true
symbol = "󰹧 "

[pulumi]
disabled = true

[purescript]
disabled = true
symbol = " "

[python]
symbol = " "

[quarto]
disabled = true

[rlang]
symbol = " "

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true
symbol = " "

[rust]
symbol = " "

[scala]
disabled = true
symbol = " "

[shell]

[shlvl]
disabled = false
format = "$symbol"
repeat = true
symbol = ""
repeat_offset = 1
threshold = 0

[singularity]
symbol = "󱕯 "

[solidity]
disabled = true

[spack]
disabled = true

[status]
disabled = false
symbol = " "
success_symbol = " "
not_executable_symbol = " "
not_found_symbol = " "
sigint_symbol = "󰚛 "
signal_symbol = " "
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true

[sudo]
style = 'bold red'
symbol = '󱓬 '
disabled = false

[swift]
disabled = true

[terraform]
symbol = " "

[time]
disabled = false
use_12hr = true

[typst]

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = true

[vagrant]

[vlang]
disabled = true
symbol = " "

[vcsh]
disabled = true

[zig]
disabled = true
symbol = " "

